version: 2
jobs:
  test:
    working_directory: ~/common-diagnostics
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/common-diagnostics/.npmrc
      - run:
          name: Set Registry
          command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test

  whitesource:
    working_directory: ~/common-diagnostics
    docker:
      - image: circleci/openjdk:8-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/common-diagnostics/workspace
      - run :
          name: Setup WhiteSource
          command: curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/wss_agent.sh
      - run:
          name: execute whitesource
          command: |
            cd .whitesource/
            chmod +x wss_agent.sh && ./wss_agent.sh -apiKey $WHITESOURCE_API_KEY -c ./whitesource-fs-agent.config  -project common-diagnostics -f files.list

  publish:
    working_directory: ~/common-diagnostics
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Append CircleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "const currentVersion=require('./package.json').version; const firstTwoDots=currentVersion.substring(0, currentVersion.lastIndexOf('.')+1); console.log(firstTwoDots);")$CIRCLE_BUILD_NUM
      - run:
          name: Authenticate with registry
          command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/common-diagnostics/.npmrc
      - run:
          name: Publish package to Artifactory
          command: npm publish

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - whitesource:
          requires:
            - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                  - master
